# Generated by Django 3.2.12 on 2024-07-19 12:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WiremockStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('request', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
